<?php

class CategoriesTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('categories')->delete();
        
		\DB::table('categories')->insert(array (
			0 => 
			array (
				'id' => 17,
				'name' => 'Alloy Image Box',
				'short_name' => 'alloy-image-box',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 3,
				'parent_id' => 0,
				'menu_id' => 33,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:54:21',
			),
			1 => 
			array (
				'id' => 18,
				'name' => 'Acrylic Photo',
				'short_name' => 'acrylic-photo',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 4,
				'parent_id' => 0,
				'menu_id' => 32,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:54:17',
			),
			2 => 
			array (
				'id' => 19,
				'name' => 'Wood Prints',
				'short_name' => 'wood-prints',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 6,
				'parent_id' => 0,
				'menu_id' => 31,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:54:14',
			),
			3 => 
			array (
				'id' => 21,
				'name' => 'Shaped ImageStylor Canvas',
				'short_name' => 'shaped-imagestylor-canvas',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 2,
				'parent_id' => 0,
				'menu_id' => 30,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:54:11',
			),
			4 => 
			array (
				'id' => 28,
				'name' => 'ImageStyle',
				'short_name' => 'imagestyle',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 5,
				'parent_id' => 0,
				'menu_id' => 29,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:54:06',
			),
			5 => 
			array (
				'id' => 29,
				'name' => 'Wall Collage',
				'short_name' => 'wall-collage',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 10,
				'parent_id' => 0,
				'menu_id' => 28,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:54:03',
			),
			6 => 
			array (
				'id' => 30,
				'name' => 'Canvas Prints',
				'short_name' => 'canvas-prints',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 0,
				'parent_id' => 18,
				'menu_id' => 27,
				'active' => 0,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:54:00',
			),
			7 => 
			array (
				'id' => 36,
				'name' => 'Tri-Photo HBL',
				'short_name' => 'triphoto-hbl',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 8,
				'parent_id' => 0,
				'menu_id' => 26,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:53:57',
			),
			8 => 
			array (
				'id' => 37,
				'name' => 'Smart Plaque',
				'short_name' => 'smart-plaque',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 7,
				'parent_id' => 0,
				'menu_id' => 25,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:53:53',
			),
			9 => 
			array (
				'id' => 42,
				'name' => 'Graphic Prints Collection',
				'short_name' => 'graphic-prints-collection',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 0,
				'parent_id' => 0,
				'menu_id' => 24,
				'active' => 0,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:53:50',
			),
			10 => 
			array (
				'id' => 43,
				'name' => 'Wall Splits',
				'short_name' => 'wall-splits',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 9,
				'parent_id' => 0,
				'menu_id' => 23,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:53:44',
			),
			11 => 
			array (
				'id' => 47,
				'name' => 'Paper Prints',
				'short_name' => 'paper-prints',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 1,
				'parent_id' => 17,
				'menu_id' => 22,
				'active' => 0,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:53:41',
			),
			12 => 
			array (
				'id' => 49,
				'name' => 'Greeting Cards',
				'short_name' => 'greeting-cards',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 1,
				'parent_id' => 37,
				'menu_id' => 21,
				'active' => 0,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:53:38',
			),
			13 => 
			array (
				'id' => 51,
				'name' => 'ImageStylor Canvas',
				'short_name' => 'imagestylor-canvas',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 1,
				'parent_id' => 0,
				'menu_id' => 20,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 06:53:34',
			),
			14 => 
			array (
				'id' => 52,
				'name' => 'Triangle Wall Collage',
				'short_name' => 'triangle-wall-collage',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 0,
				'parent_id' => 29,
				'menu_id' => 19,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 07:10:44',
			),
			15 => 
			array (
				'id' => 53,
				'name' => 'Tritych ImageStylor Canvas Clusters',
				'short_name' => 'tritych-imagestylor-canvas-clusters',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 0,
				'parent_id' => 0,
				'menu_id' => 18,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 10:06:49',
			),
			16 => 
			array (
				'id' => 56,
				'name' => '4 Square Imagestylor Canvas Cluster',
				'short_name' => '4-square-imagestylor-canvas-cluster',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 1,
				'parent_id' => 0,
				'menu_id' => 17,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 10:07:02',
			),
			17 => 
			array (
				'id' => 57,
				'name' => 'Modern Imagestylor Canvas Cluster',
				'short_name' => 'modern-imagestylor-canvas-cluster',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 3,
				'parent_id' => 0,
				'menu_id' => 16,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 10:07:15',
			),
			18 => 
			array (
				'id' => 58,
				'name' => 'Stair Climber ImageStylor Canvas Clusters',
				'short_name' => 'stair-climber-imagestylor-canvas-clusters',
				'meta_title' => NULL,
				'meta_description' => '',
				'order_no' => 4,
				'parent_id' => 0,
				'menu_id' => 15,
				'active' => 1,
				'created_by' => 8,
				'updated_by' => 3,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-04-17 10:07:25',
			),
		));
	}

}
