<?php

class MenusTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('menus')->delete();

		\DB::table('menus')->insert(array (
			0 =>
			array (
				'id' => 1,
				'name' => 'Dashboard',
				'icon_class' => 'icon-home',
				'link' => 'admin',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 1,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:01',
				'updated_at' => '2015-04-24 03:05:58',
			),
			1 =>
			array (
				'id' => 2,
				'name' => 'Configure',
				'icon_class' => 'fa fa-cogs',
				'link' => 'admin/configures',
				'parent_id' => 55,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:59',
			),
			2 =>
			array (
				'id' => 3,
				'name' => 'Banner',
				'icon_class' => 'icon-credit-card',
				'link' => 'admin/banners',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:59',
			),
			3 =>
			array (
				'id' => 4,
				'name' => 'Menu',
				'icon_class' => 'icon-list',
				'link' => 'admin/menus',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 2,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:58',
			),
			4 =>
			array (
				'id' => 5,
				'name' => 'User',
				'icon_class' => 'icon-users',
				'link' => 'admin/users',
				'parent_id' => 55,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:59',
			),
			5 =>
			array (
				'id' => 6,
				'name' => 'Admin',
				'icon_class' => 'fa fa-users',
				'link' => 'admin/admins',
				'parent_id' => 55,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:59',
			),
			6 =>
			array (
				'id' => 7,
				'name' => 'Products Group',
				'icon_class' => 'icon-social-dropbox',
				'link' => NULL,
				'parent_id' => 0,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 3,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:58',
			),
			7 =>
			array (
				'id' => 8,
				'name' => 'Product',
				'icon_class' => 'icon-bag',
				'link' => 'admin/products',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:58',
			),
			8 =>
			array (
				'id' => 9,
				'name' => 'Option Group',
				'icon_class' => 'icon-notebook',
				'link' => 'admin/product-option-groups',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:58',
			),
			9 =>
			array (
				'id' => 10,
				'name' => 'Option',
				'icon_class' => 'icon-layers',
				'link' => 'admin/product-options',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:58',
			),
			10 =>
			array (
				'id' => 11,
				'name' => 'Category',
				'icon_class' => 'icon-bar-chart',
				'link' => 'admin/product-categories',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => '',
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:09:24',
			),
			11 =>
			array (
				'id' => 12,
				'name' => 'Layout',
				'icon_class' => 'icon-screen-tablet',
				'link' => '',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => '',
				'order_no' => 5,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:59',
			),
			12 =>
			array (
				'id' => 13,
				'name' => 'Pages',
				'icon_class' => 'icon-docs',
				'link' => NULL,
				'parent_id' => 52,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:59',
			),
			13 =>
			array (
				'id' => 14,
				'name' => 'Static Page',
				'icon_class' => 'icon-doc',
				'link' => 'admin/pages',
				'parent_id' => 13,
				'type' => 'backend',
				'group' => NULL,
				'order_no' => 1,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-16 08:27:02',
				'updated_at' => '2015-04-24 03:05:59',
			),
			14 =>
			array (
				'id' => 15,
				'name' => 'Stair Climber ImageStylor Canvas',
				'icon_class' => 'icon-settings',
				'link' => 'collections/stair-climber-imagestylor-canvas-clusters',
				'parent_id' => 36,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 3,
				'created_at' => '2015-04-17 06:53:17',
				'updated_at' => '2015-04-21 07:35:24',
			),
			15 =>
			array (
				'id' => 16,
				'name' => 'Modern Imagestylor Canvas Clusters',
				'icon_class' => 'icon-settings',
				'link' => 'collections/modern-imagestylor-canvas-cluster',
				'parent_id' => 36,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 3,
				'created_at' => '2015-04-17 06:53:21',
				'updated_at' => '2015-04-21 07:35:24',
			),
			16 =>
			array (
				'id' => 17,
				'name' => '4 Square Imagestylor Canvas Clusters',
				'icon_class' => 'icon-settings',
				'link' => 'collections/4-square-imagestylor-canvas-cluster',
				'parent_id' => 36,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 3,
				'created_at' => '2015-04-17 06:53:25',
				'updated_at' => '2015-04-21 07:35:24',
			),
			17 =>
			array (
				'id' => 18,
				'name' => 'Tritych Imagestylor Canvas Clusters',
				'icon_class' => 'icon-settings',
				'link' => 'collections/tritych-imagestylor-canvas-clusters',
				'parent_id' => 36,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 3,
				'created_at' => '2015-04-17 06:53:29',
				'updated_at' => '2015-04-21 07:35:24',
			),
			18 =>
			array (
				'id' => 19,
				'name' => 'Triangle Wall Collage',
				'icon_class' => 'icon-settings',
				'link' => 'collections/triangle-wall-collage',
				'parent_id' => 35,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 3,
				'created_at' => '2015-04-17 06:53:31',
				'updated_at' => '2015-04-21 07:35:24',
			),
			19 =>
			array (
				'id' => 20,
				'name' => 'ImageStylor Canvas',
				'icon_class' => '',
				'link' => 'collections/imagestylor-canvas',
				'parent_id' => 34,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:53:34',
				'updated_at' => '2015-04-21 07:35:24',
			),
			20 =>
			array (
				'id' => 21,
				'name' => 'Greeting Cards',
				'icon_class' => '',
				'link' => 'collections/greeting-cards',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 8,
				'level' => 1,
				'active' => 0,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:53:38',
				'updated_at' => '2015-04-21 07:35:24',
			),
			21 =>
			array (
				'id' => 22,
				'name' => 'Paper Prints',
				'icon_class' => '',
				'link' => 'collections/paper-prints',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 9,
				'level' => 1,
				'active' => 0,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:53:40',
				'updated_at' => '2015-04-21 07:35:24',
			),
			22 =>
			array (
				'id' => 23,
				'name' => 'Wall Splits',
				'icon_class' => '',
				'link' => 'collections/wall-splits',
				'parent_id' => 35,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:53:44',
				'updated_at' => '2015-04-21 07:35:24',
			),
			23 =>
			array (
				'id' => 24,
				'name' => 'Graphic Prints Collection',
				'icon_class' => '',
				'link' => 'collections/graphic-prints-collection',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 7,
				'level' => 1,
				'active' => 0,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:53:50',
				'updated_at' => '2015-04-21 07:35:24',
			),
			24 =>
			array (
				'id' => 25,
				'name' => 'Smart Plaque',
				'icon_class' => '',
				'link' => 'collections/smart-plaque',
				'parent_id' => 34,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 7,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:53:53',
				'updated_at' => '2015-04-21 07:35:24',
			),
			25 =>
			array (
				'id' => 26,
				'name' => 'Tri-Photo HBL',
				'icon_class' => '',
				'link' => 'collections/triphoto-hbl',
				'parent_id' => 34,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 8,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:53:57',
				'updated_at' => '2015-04-21 07:35:24',
			),
			26 =>
			array (
				'id' => 27,
				'name' => 'Canvas Prints',
				'icon_class' => '',
				'link' => 'collections/canvas-prints',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 6,
				'level' => 1,
				'active' => 0,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:54:00',
				'updated_at' => '2015-04-21 07:35:24',
			),
			27 =>
			array (
				'id' => 28,
				'name' => 'Wall Collage',
				'icon_class' => '',
				'link' => 'collections/wall-collage',
				'parent_id' => 35,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:54:02',
				'updated_at' => '2015-04-21 07:35:24',
			),
			28 =>
			array (
				'id' => 29,
				'name' => 'ImageStyle',
				'icon_class' => '',
				'link' => 'collections/imagestyle',
				'parent_id' => 34,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 5,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:54:06',
				'updated_at' => '2015-04-21 07:35:24',
			),
			29 =>
			array (
				'id' => 30,
				'name' => 'Shaped ImageStylor Canvas',
				'icon_class' => '',
				'link' => 'collections/shaped-imagestylor-canvas',
				'parent_id' => 34,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:54:10',
				'updated_at' => '2015-04-21 07:35:24',
			),
			30 =>
			array (
				'id' => 31,
				'name' => 'Wood Prints',
				'icon_class' => '',
				'link' => 'collections/wood-prints',
				'parent_id' => 34,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 6,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:54:14',
				'updated_at' => '2015-04-21 07:35:24',
			),
			31 =>
			array (
				'id' => 32,
				'name' => 'Acrylic Photo',
				'icon_class' => '',
				'link' => 'collections/acrylic-photo',
				'parent_id' => 34,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:54:17',
				'updated_at' => '2015-04-21 07:35:24',
			),
			32 =>
			array (
				'id' => 33,
				'name' => 'Alloy Image Box',
				'icon_class' => '',
				'link' => 'collections/alloy-image-box',
				'parent_id' => 34,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 06:54:21',
				'updated_at' => '2015-04-21 07:35:24',
			),
			33 =>
			array (
				'id' => 34,
				'name' => 'Products',
				'icon_class' => 'icon-social-dropbox',
				'link' => '',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 2,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 07:03:29',
				'updated_at' => '2015-04-21 07:35:24',
			),
			34 =>
			array (
				'id' => 35,
				'name' => 'Collections',
				'icon_class' => 'icon-user',
				'link' => '',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 4,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 07:04:05',
				'updated_at' => '2015-04-21 07:35:24',
			),
			35 =>
			array (
				'id' => 36,
				'name' => 'Wall Clusters',
				'icon_class' => 'icon-user',
				'link' => '',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 3,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 07:04:25',
				'updated_at' => '2015-04-21 07:35:24',
			),
			36 =>
			array (
				'id' => 37,
				'name' => 'User Feedback',
				'icon_class' => 'icon-feed',
				'link' => 'admin/contacts',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => '',
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-20 08:06:32',
				'updated_at' => '2015-04-24 03:05:59',
			),
			37 =>
			array (
				'id' => 38,
				'name' => 'Role',
				'icon_class' => 'fa fa-users',
				'link' => 'admin/roles',
				'parent_id' => 55,
				'type' => 'backend',
				'group' => '',
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-20 08:06:32',
				'updated_at' => '2015-04-24 03:05:59',
			),
			38 =>
			array (
				'id' => 39,
				'name' => 'Contact',
				'icon_class' => 'icon-settings',
				'link' => 'contact',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 5,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 1,
				'created_at' => '2015-04-21 07:34:34',
				'updated_at' => '2015-04-21 07:39:54',
			),
			39 =>
			array (
				'id' => 40,
				'name' => 'About / Visual Impact',
				'icon_class' => 'icon-settings',
				'link' => 'about-visual-impact',
				'parent_id' => 49,
				'type' => 'frontend',
				'group' => 'footer',
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 1,
				'created_at' => '2015-04-21 07:34:36',
				'updated_at' => '2015-04-21 07:40:49',
			),
			40 =>
			array (
				'id' => 42,
				'name' => 'Wholesale',
				'icon_class' => 'icon-settings',
				'link' => 'wholesale',
				'parent_id' => 49,
				'type' => 'frontend',
				'group' => 'footer',
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 1,
				'created_at' => '2015-04-21 07:34:40',
				'updated_at' => '2015-04-21 07:40:49',
			),
			41 =>
			array (
				'id' => 44,
				'name' => 'Customer Service',
				'icon_class' => 'icon-settings',
				'link' => '',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'footer',
				'order_no' => 2,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-21 07:36:42',
				'updated_at' => '2015-04-21 07:44:03',
			),
			42 =>
			array (
				'id' => 45,
				'name' => 'Home',
				'icon_class' => 'icon-settings',
				'link' => '',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'order_no' => 1,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-21 07:38:10',
				'updated_at' => '2015-04-21 07:38:10',
			),
			43 =>
			array (
				'id' => 46,
				'name' => 'Contact / Custom Orders',
				'icon_class' => 'icon-settings',
				'link' => 'contact',
				'parent_id' => 44,
				'type' => 'frontend',
				'group' => 'footer',
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-21 07:40:36',
				'updated_at' => '2015-04-21 07:44:03',
			),
			44 =>
			array (
				'id' => 47,
				'name' => 'Shipping Information',
				'icon_class' => 'icon-settings',
				'link' => 'shipping-information',
				'parent_id' => 49,
				'type' => 'frontend',
				'group' => 'footer',
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 1,
				'created_at' => '2015-04-21 07:41:45',
				'updated_at' => '2015-04-21 07:44:03',
			),
			45 =>
			array (
				'id' => 48,
				'name' => 'Terms',
				'icon_class' => 'icon-settings',
				'link' => 'terms',
				'parent_id' => 49,
				'type' => 'frontend',
				'group' => 'footer',
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 1,
				'created_at' => '2015-04-21 07:41:48',
				'updated_at' => '2015-04-21 07:44:03',
			),
			46 =>
			array (
				'id' => 49,
				'name' => 'Infomation',
				'icon_class' => 'icon-settings',
				'link' => '',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'footer',
				'order_no' => 1,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-21 07:43:53',
				'updated_at' => '2015-04-21 07:44:03',
			),
			47 =>
			array (
				'id' => 50,
				'name' => 'Box layout',
				'icon_class' => 'icon-grid',
				'link' => 'admin/layouts',
				'parent_id' => 12,
				'type' => 'backend',
				'group' => '',
				'order_no' => 1,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-24 03:01:52',
				'updated_at' => '2015-04-24 03:07:46',
			),
			48 =>
			array (
				'id' => 51,
				'name' => 'Shape Layout',
				'icon_class' => 'icon-star',
				'link' => 'admin/shape-layouts',
				'parent_id' => 12,
				'type' => 'backend',
				'group' => '',
				'order_no' => 2,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-24 03:02:58',
				'updated_at' => '2015-04-24 03:07:58',
			),
			49 =>
			array (
				'id' => 52,
				'name' => 'Other Content',
				'icon_class' => 'icon-settings',
				'link' => '',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 4,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-24 03:03:32',
				'updated_at' => '2015-04-24 03:05:59',
			),
			50 =>
			array (
				'id' => 53,
				'name' => 'Order',
				'icon_class' => 'icon-basket-loaded',
				'link' => 'admin/orders',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => '',
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-24 03:04:31',
				'updated_at' => '2015-04-24 03:06:37',
			),
			51 =>
			array (
				'id' => 54,
				'name' => 'Email Template',
				'icon_class' => 'icon-envelope',
				'link' => 'admin/email-templates',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => '',
				'order_no' => 5,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-24 03:05:11',
				'updated_at' => '2015-04-24 03:08:14',
			),
			52 =>
			array (
				'id' => 55,
				'name' => 'Admin Group',
				'icon_class' => 'icon-settings',
				'link' => '',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'order_no' => 5,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-24 03:05:34',
				'updated_at' => '2015-04-24 03:05:59',
			),
		));
	}

}
